### ISSUE TITLE
一直失败

### ISSUE THREAD

**Issue by zayn-0101** [malinkang/keep2notion#1]
请教下作者，一直失败，不知是什么原因呢
<img width="1018" alt="截屏2024-04-02 01 00 16" src="https://github.com/malinkang/keep2notion/assets/2428630/6eba223c-69a0-4d68-8c41-0e2d75c8adae">

**Comment by malinkang** [comment]
因为你今年还没有跑步

**Comment by zayn-0101** [comment]
> 因为你今年还没有跑步

😯 原来如此！
